# Generated by Django 5.0.3 on 2024-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caroffer',
            name='cars',
        ),
        migrations.AddField(
            model_name='caroffer',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Tesla', 'Tesla'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Lexus', 'Lexus'), ('Jeep', 'Jeep'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
