# Generated by Django 5.0.3 on 2024-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_caroffer_cars_caroffer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroffer',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
