# Generated by Django 5.0.3 on 2024-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_caroffer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='car_photo',
            field=models.URLField(),
        ),
    ]
