# Generated by Django 5.0.3 on 2024-04-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_caroffer_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caroffer',
            name='slug',
        ),
    ]
