# Generated by Django 5.0.3 on 2024-04-10 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Tesla', 'Tesla'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Lexus', 'Lexus'), ('Jeep', 'Jeep'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche')], max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('year_of_production', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
