# Generated by Django 5.0.3 on 2024-04-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_model_remove_car_year_of_production'),
        ('offers', '0002_remove_caroffer_cars_caroffer_brand'),
        ('web', '0002_alter_offercomment_car_offer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
