# Generated by Django 5.0.3 on 2024-04-11 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_caroffer_user'),
        ('web', '0002_alter_offercomment_car_offer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlike',
            name='car_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.caroffer'),
        ),
        migrations.AlterField(
            model_name='offerlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
