# Generated by Django 5.0.3 on 2024-04-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_offerlike_car_offer_alter_offerlike_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offercomment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
