# Generated by Django 5.0.3 on 2024-04-04 12:31

import DjigitAuto.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjigitAutoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=20, unique=True, validators=[DjigitAuto.accounts.models.validate_username])),
                ('first_name', models.CharField(blank=True, max_length=20, validators=[DjigitAuto.accounts.models.validate_user_last_first_name])),
                ('last_name', models.CharField(blank=True, max_length=20, validators=[DjigitAuto.accounts.models.validate_user_last_first_name])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
