# Generated by Django 5.0.3 on 2024-04-04 12:55

import DjigitAuto.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_djigitautouser_groups_djigitautouser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djigitautouser',
            managers=[
                ('object', DjigitAuto.accounts.models.DjigitAutoUserManager()),
            ],
        ),
    ]
