# Generated by Django 5.0.3 on 2024-04-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_djigitautouser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='djigitautouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='djigitautouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
