# Generated by Django 5.0.3 on 2024-04-05 13:55

import DjigitAuto.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_djigitautouser_is_active_djigitautouser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djigitautouser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Username:', max_length=20, unique=True, validators=[DjigitAuto.accounts.models.validate_username]),
        ),
    ]
