# Generated by Django 5.0.3 on 2024-04-08 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_remove_djigitautouser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djigitautouser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
