# Generated by Django 5.0.3 on 2024-04-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_djigitautouser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='djigitautouser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
